const images = `https://hpwren.ucsd.edu/cameras/L/bm-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bm-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bm-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bm-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bi-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bi-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bi-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bi-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bl-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bl-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bl-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bl-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bh-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bh-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bh-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bh-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/buff-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/buff-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/buff-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/buff-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/chino-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/chino-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/chino-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/chino-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ch-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ch-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ch-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ch-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/cp-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/cp-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/cp-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/cp-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/dwpgm-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/dwpgm-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/dwpgm-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/dwpgm-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/hp-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/hp-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/hp-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/hp-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/69bravo-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/69bravo-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/69bravo-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/69bravo-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wlfd-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wlfd-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wlfd-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wlfd-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/pi-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/pi-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/pi-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/pi-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/lp-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/lp-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/lp-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/lp-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mg-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mg-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mg-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mg-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ml-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ml-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ml-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ml-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wc-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wc-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wc-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wc-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mlo-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mlo-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mlo-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/mlo-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wilson-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wilson-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wilson-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/wilson-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/om-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/om-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/om-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/om-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rm-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rm-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rm-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rm-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rdd-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rdd-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rdd-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/rdd-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smernsp-sw-u180-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs9-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs9-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs9-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs9-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sclm-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sclm-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sclm-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sclm-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sjh-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sjh-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sjh-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sjh-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sm-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sm-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sm-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sm-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/syp-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/syp-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/syp-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/syp-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/stgo-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/stgo-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/stgo-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/stgo-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sr-ne-u180-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sr-sw-u180-175.jpg
  https://hpwren.ucsd.edu/cameras/L/signal-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/signal-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/signal-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/signal-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sojr-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sojr-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sojr-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sojr-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/tp-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/tp-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/tp-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/tp-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/starr-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/starr-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/starr-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/starr-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/marconi-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/marconi-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/marconi-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/marconi-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/vo-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/vo-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/vo-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/vo-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ws-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ws-e-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ws-s-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ws-w-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bc-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bc-2-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bc-3-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bc-4-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/bc-5-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/hpwren-iqeye8-175.jpg
  https://hpwren.ucsd.edu/cameras/L/ms-n-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sgbf-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs10-1-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs3-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/smer-tcs8-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/tje-1-mobo-c-175.jpg
  https://hpwren.ucsd.edu/cameras/L/sdsc-e-mobo-c-175.jpg`.split("\n");
